---@meta

---@class UDebugScreen_BP_C : UDebugScreen
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AIActionRepeatCheckBox UCheckBox
---@field AIActionRepeatDelaySpinBox USpinBox
---@field AICharacterTypeComboBox UComboBoxString
---@field ApplyClothingButton UNavButton
---@field ApplyEmotesButton UNavButton
---@field ApplyEvilEffectsButton UNavButton
---@field ApplyEvilSkinButton UNavButton
---@field ApplySpectralsButton UNavButton
---@field ApplyStickersButton UNavButton
---@field ApplyWeaponSkinButton UNavButton
---@field ButtonAddRage UNavButton
---@field ButtonCowering UNavButton
---@field ButtonDeath UNavButton
---@field ButtonDebugDarkShard UNavButton
---@field ButtonDisintegrate UNavButton
---@field ButtonElectrocute UNavButton
---@field ButtonEvilCamera UNavButton
---@field ButtonEvilDeath UNavButton
---@field ButtonFlinch UNavButton
---@field ButtonForceCooldowns UNavButton
---@field ButtonGooped UNavButton
---@field ButtonIncorporeal UNavButton
---@field ButtonInjury UNavButton
---@field ButtonKillAI UNavButton
---@field ButtonKillTeens UNavButton
---@field ButtonKillWerewolf UNavButton
---@field ButtonMotionSentinel UNavButton
---@field ButtonPlayTVIntro UNavButton
---@field ButtonPossessAI UNavButton
---@field ButtonProne UNavButton
---@field ButtonRemoveRage UNavButton
---@field ButtonResetCooldowns UNavButton
---@field ButtonScream UNavButton
---@field ButtonSpawnAI UNavButton
---@field ButtonSpawnJock UNavButton
---@field ButtonSpawnWerewolf UNavButton
---@field ButtonStaggered UNavButton
---@field ButtonStartPlayback UNavButton
---@field ButtonStartRecording UNavButton
---@field ButtonStopPlayback UNavButton
---@field ButtonStopRecording UNavButton
---@field ButtonStun UNavButton
---@field ButtonSubdued UNavButton
---@field ButtonSummonAI UNavButton
---@field ButtonToggleCharVis UNavButton
---@field ButtonToggleFPS UNavButton
---@field ButtonToggleFrozen UNavButton
---@field ButtonTritonDebug UNavButton
---@field CategoryLeftButton UNavButton
---@field CategoryRightButton UNavButton
---@field DebugLeftImage UImage
---@field DebugRightImage UImage
---@field EvilButton0 UNavButton
---@field EvilButton1 UNavButton
---@field EvilButton2 UNavButton
---@field EvilButton3 UNavButton
---@field EvilButton4 UNavButton
---@field RandomClothingButton UNavButton
---@field RandomClothingCycleCheckBox UCheckBox
---@field SelectableAIComboBox UComboBoxString
---@field SurvivorButton0 UNavButton
---@field SurvivorButton1 UNavButton
---@field SurvivorButton2 UNavButton
---@field SurvivorButton3 UNavButton
---@field SurvivorButton4 UNavButton
---@field SurvivorButton5 UNavButton
---@field SurvivorButton6 UNavButton
---@field SurvivorButton7 UNavButton
---@field WeaponButton0 UNavButton
---@field WeaponButton1 UNavButton
---@field WeaponButton10 UNavButton
---@field WeaponButton11 UNavButton
---@field WeaponButton12 UNavButton
---@field WeaponButton2 UNavButton
---@field WeaponButton3 UNavButton
---@field WeaponButton4 UNavButton
---@field WeaponButton5 UNavButton
---@field WeaponButton6 UNavButton
---@field WeaponButton7 UNavButton
---@field WeaponButton8 UNavButton
---@field WeaponButton9 UNavButton
---@field WeaponText UTextBlock
---@field ['Key Name'] FName
---@field ['Gameplay Tag'] FGameplayTag
UDebugScreen_BP_C = {}

function UDebugScreen_BP_C:BndEvt__DebugScreen_BP_ButtonKillWerewolf_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature() end
function UDebugScreen_BP_C:BndEvt__DebugScreen_BP_ButtonSpawnWerewolf_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature() end
function UDebugScreen_BP_C:BndEvt__DebugScreen_BP_ButtonSpawnJock_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature() end
function UDebugScreen_BP_C:BndEvt__DebugScreen_BP_ButtonKillTeens_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature() end
---@param EntryPoint int32
function UDebugScreen_BP_C:ExecuteUbergraph_DebugScreen_BP(EntryPoint) end


