---@meta

---@class UFPChar_DOLL_AnimBP_C : UDollMinionAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_TransitionResult_28 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_27 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_26 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_25 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_24 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_23 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_22 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_21 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_20 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_19 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_18 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_17 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_16 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_14 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_18 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_13 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_17 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_12 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_16 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_11 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_15 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_10 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByInt FAnimNode_BlendListByInt
---@field AnimGraphNode_SequencePlayer_9 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_14 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_8 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_13 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_12 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_11 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_10 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_3 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_RandomPlayer FAnimNode_RandomPlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_2 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field LobbyPoseIndex int32
---@field SwayEnabled boolean
---@field AnimData FFPCharAnimInstanceData
---@field ['Delta X'] float
---@field TimingActive boolean
---@field TimeStarted float
UFPChar_DOLL_AnimBP_C = {}

---@param AnimGraph FPoseLink
function UFPChar_DOLL_AnimBP_C:AnimGraph(AnimGraph) end
function UFPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_FPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_23B57DFD429E51857B9766AEADA57812() end
function UFPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_FPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_0FD054184F53F37217D0D5BBB17F0CC0() end
function UFPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_FPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_980043894D2B4D2A75F4EBA8544014B2() end
function UFPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_FPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_0C663BC84DE7BC5534CA72A08FF58135() end
function UFPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_FPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_E807C1EF4C28DAE6016F11848DBC2A4E() end
function UFPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_FPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_4D68463D4D6B688BFD9CE699D9ED23E8() end
function UFPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_FPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_192F469645AAC78DB35B39BF9283168F() end
function UFPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_FPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_26C7D2F0481852E906F8788821D4F627() end
---@param DeltaTimeX float
function UFPChar_DOLL_AnimBP_C:BlueprintUpdateAnimation(DeltaTimeX) end
---@param EntryPoint int32
function UFPChar_DOLL_AnimBP_C:ExecuteUbergraph_FPChar_DOLL_AnimBP(EntryPoint) end


