---@meta

---@class UTP_TEEN_Height_Curves_AnimBP_C : UAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_ModifyBone_7 FAnimNode_ModifyBone
---@field AnimGraphNode_LocalToComponentSpace_14 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ModifyBone_6 FAnimNode_ModifyBone
---@field AnimGraphNode_SaveCachedPose_13 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_26 FAnimNode_UseCachedPose
---@field AnimGraphNode_ComponentToLocalSpace_14 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_SaveCachedPose_12 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendListByBool_4 FAnimNode_BlendListByBool
---@field AnimGraphNode_ComponentToLocalSpace_13 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LocalToComponentSpace_13 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_SaveCachedPose_11 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LocalToComponentSpace_12 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_SaveCachedPose_10 FAnimNode_SaveCachedPose
---@field AnimGraphNode_ComponentToLocalSpace_12 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_UseCachedPose_25 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_24 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_9 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LocalToComponentSpace_11 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_11 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TwoWayBlend_7 FAnimNode_TwoWayBlend
---@field AnimGraphNode_SaveCachedPose_8 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendListByBool_3 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_23 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_22 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_10 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_10 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_SaveCachedPose_7 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SaveCachedPose_6 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LocalToComponentSpace_9 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_9 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TwoWayBlend_6 FAnimNode_TwoWayBlend
---@field AnimGraphNode_UseCachedPose_21 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_8 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_8 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_UseCachedPose_20 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_19 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_7 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_7 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TwoWayBlend_5 FAnimNode_TwoWayBlend
---@field AnimGraphNode_LocalToComponentSpace_6 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_6 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TwoWayBlend_4 FAnimNode_TwoWayBlend
---@field AnimGraphNode_UseCachedPose_18 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_5 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_17 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_16 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_5 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_5 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TwoWayBlend_3 FAnimNode_TwoWayBlend
---@field AnimGraphNode_LocalToComponentSpace_4 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_4 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TwoWayBlend_2 FAnimNode_TwoWayBlend
---@field AnimGraphNode_LocalToComponentSpace_3 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_3 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TwoWayBlend_1 FAnimNode_TwoWayBlend
---@field AnimGraphNode_LocalToComponentSpace_2 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_2 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TwoWayBlend FAnimNode_TwoWayBlend
---@field AnimGraphNode_UseCachedPose_15 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_14 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_13 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_4 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_12 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_11 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_10 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_3 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_9 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_8 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_7 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_SubInput FAnimNode_LinkedInputPose
---@field AnimGraphNode_RotationOffsetBlendSpace FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_CopyBone_33 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_32 FAnimNode_CopyBone
---@field AnimGraphNode_LocalToComponentSpace_1 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_1 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_CopyBone_31 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_30 FAnimNode_CopyBone
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_CopyBone_29 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_28 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_27 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_26 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_25 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_24 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_23 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_22 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_21 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_20 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_19 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_18 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_17 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_16 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_15 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_14 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_13 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_12 FAnimNode_CopyBone
---@field AnimGraphNode_TwoBoneIK_9 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK_8 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK_7 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK_6 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK_5 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK_4 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK_3 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK_2 FAnimNode_TwoBoneIK
---@field AnimGraphNode_CopyBone_11 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_10 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_9 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_8 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_7 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_6 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_5 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_4 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_3 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_2 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone_1 FAnimNode_CopyBone
---@field AnimGraphNode_CopyBone FAnimNode_CopyBone
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_ModifyBone_5 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_4 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_3 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_2 FAnimNode_ModifyBone
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_TwoBoneIK_1 FAnimNode_TwoBoneIK
---@field AnimGraphNode_ModifyBone_1 FAnimNode_ModifyBone
---@field AnimGraphNode_TwoBoneIK FAnimNode_TwoBoneIK
---@field AnimGraphNode_ModifyBone FAnimNode_ModifyBone
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field ['Master Switch'] boolean
---@field ['IK Switch'] boolean
---@field Shoulder_Translation FVector
---@field Shoulders float
---@field CurrentHeight float
---@field IKControllerNames TMap<FName, FName>
---@field MovementData FTPMovementData
---@field BodyShapeData FCharacterBodyShapePreset
---@field PelvisIKWorldAlpha float
---@field HandIKGroundR float
---@field HandIKWorldR float
---@field FootIKGroundR float
---@field FootIKWorldR float
---@field HandIKGroundL float
---@field HandIKWorldL float
---@field FootIKGroundL float
---@field FootIKWorldL float
---@field HeelHeightAlpha float
---@field Timer float
---@field TimeToRefreshAlphas float
---@field IsInGame boolean
---@field UseGroundCurves boolean
UTP_TEEN_Height_Curves_AnimBP_C = {}

---@param InPose FPoseLink
---@param AnimGraph FPoseLink
function UTP_TEEN_Height_Curves_AnimBP_C:AnimGraph(InPose, AnimGraph) end
function UTP_TEEN_Height_Curves_AnimBP_C:UpdateLocalVariables() end
function UTP_TEEN_Height_Curves_AnimBP_C:UpdateCurveAlphas() end
function UTP_TEEN_Height_Curves_AnimBP_C:UpdateCurves() end
---@param CurveName FName
---@return FName
function UTP_TEEN_Height_Curves_AnimBP_C:GetCurveNameFromHeight(CurveName) end
function UTP_TEEN_Height_Curves_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TP_TEEN_Height_Curves_AnimBP_AnimGraphNode_ModifyBone_92E14FE448ADE6AC1AA5FBA1FDF77358() end
function UTP_TEEN_Height_Curves_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TP_TEEN_Height_Curves_AnimBP_AnimGraphNode_TwoBoneIK_393A2CD340EFBC96989AA299E6A5ADBA() end
function UTP_TEEN_Height_Curves_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TP_TEEN_Height_Curves_AnimBP_AnimGraphNode_ModifyBone_8D5A5EA24D8102163F55A58AE7F95277() end
function UTP_TEEN_Height_Curves_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TP_TEEN_Height_Curves_AnimBP_AnimGraphNode_TwoBoneIK_344084FE48D271622428D89A693A045F() end
function UTP_TEEN_Height_Curves_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TP_TEEN_Height_Curves_AnimBP_AnimGraphNode_ModifyBone_2DAE96E84F319FB759ABB0A75CEC41A9() end
function UTP_TEEN_Height_Curves_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TP_TEEN_Height_Curves_AnimBP_AnimGraphNode_ModifyBone_B0BCE7124E6B43EA2BE3BFB102203303() end
function UTP_TEEN_Height_Curves_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TP_TEEN_Height_Curves_AnimBP_AnimGraphNode_ModifyBone_CA2C05024262355D2091CE981475569E() end
function UTP_TEEN_Height_Curves_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TP_TEEN_Height_Curves_AnimBP_AnimGraphNode_ModifyBone_72DEA4A4436E309DF76C6B8216EE1EDF() end
function UTP_TEEN_Height_Curves_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TP_TEEN_Height_Curves_AnimBP_AnimGraphNode_ModifyBone_C6932A364EF5394A2C177198A0960989() end
---@param DeltaTimeX float
function UTP_TEEN_Height_Curves_AnimBP_C:BlueprintUpdateAnimation(DeltaTimeX) end
function UTP_TEEN_Height_Curves_AnimBP_C:BlueprintBeginPlay() end
---@param EntryPoint int32
function UTP_TEEN_Height_Curves_AnimBP_C:ExecuteUbergraph_TP_TEEN_Height_Curves_AnimBP(EntryPoint) end


