---@meta

---@class UTPChar_DOLL_AnimBP_C : UDollMinionAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_LinkedInputPose FAnimNode_LinkedInputPose
---@field AnimGraphNode_ModifyBone_1 FAnimNode_ModifyBone
---@field AnimGraphNode_LocalToComponentSpace_1 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace_1 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_Root_1 FAnimNode_Root
---@field AnimGraphNode_TransitionResult_39 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_38 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_37 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_36 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_35 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_34 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_33 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_32 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_31 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_30 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_29 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_28 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_27 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_26 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_25 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_24 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_23 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_22 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_21 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_20 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_19 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_18 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_17 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_16 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_15 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_25 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_14 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_24 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_13 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_23 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_15 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_22 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_5 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_21 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_14 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_20 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_12 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_19 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_4 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_18 FAnimNode_StateResult
---@field AnimGraphNode_StateResult_17 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_11 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_16 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_10 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_15 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_9 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_14 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_8 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_13 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_12 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_11 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_10 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_13 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_3 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_5 FAnimNode_SaveCachedPose
---@field AnimGraphNode_SubInstance FAnimNode_LinkedAnimGraph
---@field AnimGraphNode_LayeredBoneBlend_3 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_BlendListByBool_4 FAnimNode_BlendListByBool
---@field AnimGraphNode_LayeredBoneBlend_2 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_Slot_2 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_4 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendListByBool_3 FAnimNode_BlendListByBool
---@field AnimGraphNode_LinkedAnimLayer FAnimNode_LinkedAnimLayer
---@field AnimGraphNode_SaveCachedPose_3 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_12 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend_1 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_UseCachedPose_11 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_10 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_9 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_8 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_7 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_RotationOffsetBlendSpace FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_ModifyBone FAnimNode_ModifyBone
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequenceEvaluator FAnimNode_SequenceEvaluator
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_2 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field HeelHeight FVector2D
---@field __CustomProperty_HeelHeight_002D3862447B8D1906DBA1B605DCBDA7 FVector2D
---@field UseUpperBody boolean
---@field AnimData FFPCharAnimInstanceData
---@field LobbyPoseIndex int32
---@field MontagePlaying boolean
---@field UseUpperNeck boolean
---@field FPChar AFPChar
UTPChar_DOLL_AnimBP_C = {}

---@param InPose FPoseLink
---@param HeelHeight FVector2D
---@param NewAnimationLayer_0 FPoseLink
function UTPChar_DOLL_AnimBP_C:NewAnimationLayer_0(InPose, HeelHeight, NewAnimationLayer_0) end
---@param AnimGraph FPoseLink
function UTPChar_DOLL_AnimBP_C:AnimGraph(AnimGraph) end
function UTPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TPChar_DOLL_AnimBP_AnimGraphNode_ModifyBone_D1E7E4384E762DDAD7A731BB1840595A() end
function UTPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TPChar_DOLL_AnimBP_AnimGraphNode_ModifyBone_F0E2B649402D832D690372B0DB718F09() end
function UTPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_ACEF114B4AADAB4C232872B5F6D097F3() end
function UTPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_661CBC1049FE974E4F9DCBBD09F2ADC4() end
function UTPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_72DD8D544A36C21C9783F2AF76DDA805() end
function UTPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_3EA7C2FC4EA795574CB88E8B85FD3747() end
function UTPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_D84F0A684033A3B74D5CB18EA9CADB19() end
function UTPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_9B20DCE145676599A42180A075EBDA6A() end
function UTPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_71FD0D2F40402ABE76305AA0B3779344() end
function UTPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_F269E3B844959A56CFCF56904FF3A5F3() end
function UTPChar_DOLL_AnimBP_C:EvaluateGraphExposedInputs_ExecuteUbergraph_TPChar_DOLL_AnimBP_AnimGraphNode_TransitionResult_F6664E704ABE829E849400B8B29C82CE() end
---@param DeltaTimeX float
function UTPChar_DOLL_AnimBP_C:BlueprintUpdateAnimation(DeltaTimeX) end
function UTPChar_DOLL_AnimBP_C:BlueprintBeginPlay() end
---@param EntryPoint int32
function UTPChar_DOLL_AnimBP_C:ExecuteUbergraph_TPChar_DOLL_AnimBP(EntryPoint) end


